AWSTemplateFormatVersion: 2010-09-09
Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties: 
      Name: WebACL
      DefaultAction: 
        Allow: {}
      Scope: CLOUDFRONT
      VisibilityConfig: 
          CloudWatchMetricsEnabled: false
          MetricName: test-webacl-01
          SampledRequestsEnabled: false
  ProductionWebAppCloudFront:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Comment: 'Production WebApp'
        Enabled: 'true'
        HttpVersion: 'http2'
        DefaultRootObject: 'index.html'
        WebACLId: !GetAtt WebACL.Arn
        Origins:
          - DomainName: 'ProductionWebAppS3Bucket.DomainName'
            Id: 'i-0000faf7cee74697b'
            CustomOriginConfig:
              OriginProtocolPolicy: match-viewer
            OriginPath: '/app'
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD]
          TargetOriginId: 'i-0000faf7cee74697b'
          ViewerProtocolPolicy: "redirect-to-https"
          CachePolicyId: '658327ea-f89d-4fab-a63d-7e88639e58f6' # CachingOptimized
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        
 